### ISSUE TITLE
Query refresh

### ISSUE THREAD

**Issue by ricardomartinezmontero** [K-Phoen/grabana#127]
It would be great to be able to configure queries to be refreshed every time the time range changes.

https://github.com/K-Phoen/grabana/blob/36308c050d77bf49b32812b282a78845b253be29/variable/query/query.go#L64

**Comment by K-Phoen** [comment]
Hey,

That's possible :)

The line you highlighted is the default configuration set by grabana. You can override it by using the `Refresh()` option on the variable definition: `Refresh(TimeChange)`
