### ISSUE TITLE
Support for "logs" panel

### ISSUE THREAD

**Issue by atlee19** [K-Phoen/grabana#135]
It would be great to have support for the [logs panel](https://grafana.com/docs/grafana/latest/visualizations/logs-panel/)

**Comment by K-Phoen** [comment]
Definitely!

Is it something you'd be interested in contributing? (I can help)

**Comment by K-Phoen** [comment]
Implemented in #157 and released as [v0.20.7](https://github.com/K-Phoen/grabana/releases/tag/v0.20.7)  :)
