### ISSUE TITLE
Support for templating field in a grafana dashboard

### ISSUE THREAD

**Issue by s0n00im** [K-Phoen/grabana#137]
I want to add support for a dropdown inside a grafana dashboard mainly by updating the _templating_ field like this:

````
templating": {
  "list": [
   {
    "allValue": ".*",
    "current": {
     "selected": true,
     "text": "All",
     "value": [
      "$__all"
     ]
    },
"datasource": "Prometheus",
includeAll": true,
  ]
}
````

While I see support to add rows, tags, title, how do i go about adding a dropdown. I have tested the code by pasting it in a json and it does produce a dropdown.

**Comment by K-Phoen** [comment]
Hey!

Sounds like you're looking for variables: https://github.com/K-Phoen/grabana/tree/master/variable
