### ISSUE TITLE
Issues with upserting dashboard

### ISSUE THREAD

**Issue by FUSAKLA** [K-Phoen/grabana#187]
https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#rulerHi, all works like a charm, but I'm getting error when upserting dashboard. I'm not even using alerts, so maybe the functionality could be at least optional?
```
error: could not prepare deletion of previous alerts for dashboard: could not query grafana: {"message":"Not found"} (HTTP status 404)
```

If I try using cURL right on the particular query for rules:
```
curl -H "Authorization: Bearer xxx" https://foo.bar/api/ruler/grafana/api/v1/rules?dashboard_uid=ygUo8se7k
{"message":"Not found"}
```

It looks like the alerts cleanup uses [Mimir ruler](https://grafana.com/docs/mimir/latest/operators-guide/reference-http-api/#ruler) API?

I'm running self-hosted Grafana instance version 8.4.0  and using latest grabana v0.21.9 

Thanks for any pointers

**Comment by K-Phoen** [comment]
Hey!

Dashboard creation with this lib will only work if you have [Unified Alerting](https://grafana.com/blog/2021/06/14/the-new-unified-alerting-system-for-grafana-everything-you-need-to-know/) enabled, is that the case?

**Comment by FUSAKLA** [comment]
Thanks for reply!

Hmm, if it's under feature flag than nope, so that might be the case.
A page on enabling it on Grafana documentation returns 404, so I suppose it's enabled by default in the 9 release :thinking: 

Ok, I'll try upgrading and will see. 

Maybe might be worth it to mention in docs that the library is tested with 9.+ version?

**Comment by K-Phoen** [comment]
It works with 8.x, as long as the unified alerting flag is enabled :)

I'll definitely add that to the readme though :+1:

**Comment by FUSAKLA** [comment]
Right, so we can close this, and I'll reopen if the issue persists after enabling unified alerting or upgrading to 9.x 

Anyway, thanks for the library, it helped a lot and the API is really nice and well documented!
