### ISSUE TITLE
Support for Snapshots

### ISSUE THREAD

**Issue by robholland** [K-Phoen/grabana#200]
It would be useful to produce snapshots similar to the way Grabana provides upserting for dashboards.

**Comment by robholland** [comment]
https://grafana.com/docs/grafana/v9.0/developers/http_api/snapshot/

**Comment by K-Phoen** [comment]
Hey!

Could you tell me more about the use-cases you have in mind? How having the possibility to create (manage?) snapshots via Kubernetes manifests would help you?

**Comment by robholland** [comment]
This can be closed, at the time I filed this I hadn't understood that creating snapshots is done browser side. I assumed snapshot creation could be triggered via API from a command line.
