### ISSUE TITLE
Support for "stat" panel

### ISSUE THREAD

**Issue by K-Phoen** [K-Phoen/grabana#23]

**Comment by jumbogo** [comment]
So is the support for those panels implemented or still a todo?

**Comment by K-Phoen** [comment]
A "[singlestat](https://github.com/K-Phoen/grabana/tree/master/singlestat)" panel has been implemented, but I think it's actually deprecated and silently converted to a "stat" panel by Grafana.

So in terms of feature, grabana supports "stat" panels but there is some work to be done to make sure we're fully up-to-date in terms of what the library generates.

**Comment by K-Phoen** [comment]
Fixed by #170
