### ISSUE TITLE
Dump dashboard as json

### ISSUE THREAD

**Issue by varac** [K-Phoen/grabana#258]
Is there already an option to dump the generated dashboard as JSON ? If so it would be great to have this documented, I couldn't find it so far.

**Comment by K-Phoen** [comment]
You can use Go's `json.Marshal()` :)

```go
builder, err := dashboard.New(
	"Awesome dashboard",
	// ...
)
if err != nil {
	// ...
}

dashboardJSON, err := json.Marshal(builder)
if err != nil {
	// ...
}
```
