### ISSUE TITLE
Support for "heatmap" panel

### ISSUE THREAD

**Issue by K-Phoen** [K-Phoen/grabana#27]

**Comment by MichaHoffmann** [comment]
I would like to help here. Could you direct me to what is to be done? Thank you.

**Comment by MichaHoffmann** [comment]
Hey, thank you for the quick Pull Request regarding this issue! Would you also consider adding the variable type "const" and the panel type "stat"? 
If directed a little, i would be willing to help out.

**Comment by K-Phoen** [comment]
Hey!

Sorry, missed your first comment :)
The PR related to heatmaps is actually something I had in store for a couple of days as part of my day job.

"const" variables are already supported, they are named slightly differently though: https://github.com/K-Phoen/grabana/tree/master/variable/constant

For "stat" panels, I would suggest using the already implemented "singlestat" if it fits your use-cases or taking it as a source of inspiration and opening a PR for "stat" if it doesn't :)
